name: 'Slack Release Notification'
description: 'Send Slack notifications based on job status for release updates'

inputs:
  webhook-url:
    description: 'Slack webhook URL'
    required: true
  success-description:
    description: 'Description message for successful release step notification'
    required: true
  failure-description:
    description: 'Description message for failed release step notification'
    required: true
  tag:
    description: 'Release tag'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Notify Slack on Success
      if: success()
      shell: bash
      run: |
        curl -X POST -H 'Content-type: application/json' \
          --data '{
            "description": "${{ inputs.success-description }}",
            "tag": "${{ inputs.tag }}"
          }' \
          ${{ inputs.webhook-url }}

    - name: Notify Slack on Failure
      if: failure() || cancelled()
      shell: bash
      run: |
        REPO="${{ github.repository }}"
        RUN_ID="${{ github.run_id }}"
        
        curl -X POST -H 'Content-type: application/json' \
          --data '{
            "link": "https://github.com/$REPO/actions/runs/$RUN_ID",
            "description": "${{ inputs.failure-description }}",
            "tag": "${{ inputs.tag }}"
          }' \
          ${{ inputs.webhook-url }}
