name: 'Slack Release Notification'
description: 'Send Slack notifications based on job status for release updates'

inputs:
  webhook-url:
    description: 'Slack webhook URL'
    required: true
  success-description:
    description: 'Description message for successful release step notification'
    required: true
  failure-description:
    description: 'Description message for failed release step notification'
    required: true
  tag:
    description: 'Release tag'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Determine Job Status and Notify Slack
      shell: bash
      run: |
        # Check if any previous step in the job failed
        if [ "${{ job.status }}" = "success" ]; then
          echo "Job succeeded, sending success notification"
          curl -X POST -H 'Content-type: application/json' \
            --data '{
              "description": "✅ ${{ inputs.success-description }}",
              "tag": "${{ inputs.tag }}"
            }' \
            ${{ inputs.webhook-url }}
        else
          echo "Job failed or was cancelled, sending failure notification"
          REPO="${{ github.repository }}"
          RUN_ID="${{ github.run_id }}"
          
          curl -X POST -H 'Content-type: application/json' \
            --data '{
              "link": "https://github.com/$REPO/actions/runs/$RUN_ID",
              "description": "❌ ${{ inputs.failure-description }}",
              "tag": "${{ inputs.tag }}"
            }' \
            ${{ inputs.webhook-url }}
        fi
